# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
# The sum of these multiples is 23.Find the sum of all the multiples of 3 or 5 below 1000.
x = []
(0..999).each do |n|
  if n % 5 == 0 or n % 3 == 0
    x << n
  end
end

puts x.inject(:+)
# solution = 233168

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the
# even-valued terms.

fibo = []
a = (0..50).to_a

a.each_with_index { |x, index|
  if x > 2
    new_fibo = fibo[index - 1] + fibo[index - 2]
    if new_fibo >= 4000000
      break
    else
      fibo << new_fibo
      next
    end
  end
  fibo << x
}

puts fibo.keep_if { |x| x % 2 == 0 }.inject(:+)

 #solution = 4613732
